# Site settings
theme: jekyll-theme-cayman
title: Your awesome title
email: chrisfulton@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Part 1 Architect
  with background in software, teaching and visual design
baseurl: "" # the subpath of your site, e.g. /blog/
twitter_username: cj_fulton
github_username:  christopherfulton

# Build settings

